---
- name: Playbook to Add Common Criteria Policy
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - /etc/ansible/vaults/authc.vault

  tasks:
    - name: Task to Add CC Policy
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <aaa>
                  <new-model xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa"/>
                  <common-criteria xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa">
                    <policy>COMMON-POLICY</policy>
                    <char-changes>4</char-changes>
                    <max-length>127</max-length>
                    <min-length>12</min-length>
                    <restrict-consecutive-letters/>
                  </common-criteria>
                </aaa>
              </native>
            </config>
